#!/bin/bash

dotfiles=('.zsh_plugins.txt' '.zshrc' '.zshenv')

# Link .zshrc and .pairs (forced) to home
echo "!IMPORTANT! The following will be symlinked to $HOME"
echo "Existing files/symlinks will be overwritten."

for dotfile in ${dotfiles[@]}; do
  echo "${dotfile}"
done

echo ""
echo "Proceed? (Ctrl-C to abort, or press enter to continue)"
read -r

echo "Linking..."

for dotfile in ${dotfiles[@]}; do
  ln -sfv ~/.zsh.d/${dotfile} ~/${dotfile}
done

echo "Done."
ls -lsa ~/

